---
- name: 웹서버 
  gather_facts: yes
  become: yes
  hosts: all



- name: Just get information about the repository whether or not it has already been cloned locally
  ansible.builtin.git:
    repo: 'https://foosball.example.org/path/to/repo.git'
    dest: /srv/checkout
    clone: no
    update: no
