---
- name: Clone or Update and Manage Apache Web Server
  hosts: localhost
  become: true  # Privilege escalation to become root

  tasks:

    - name: CentOS > httpd
      action: "{{ ansible_pkg_mgr }} name=httpd state=present"

    - name: Clone or Update Git Repository
      ansible.builtin.git:
        repo: 'https://github.com/JaBis0125/repo.git'
        dest: /var/www/html/ansiblelab3
        clone: yes
        update: yes
      register: git_output

    - name: Restart Apache if Changes Detected
      ansible.builtin.systemd:
        name: httpd
        state: restarted
      when: git_output.changed

    - name: Debug Git Output
      ansible.builtin.debug:
        var: git_output

